fixed flow update bug
matjaz/info.matjaz.candy pull request #7
Opened 2016-10-13 20:08 UTC by irritanterik

fixed issue #4

2016-10-13 20:14 UTC, matjaz requested changes

2016-10-13 20:14 UTC, matjaz commented on lib/folderFlows.js
> +      updateFlowEnabled(flow, enabled)
thanks for debugging this.
I would change `getFolderFlows` so it returns flow not ids. As it was and name implies. Do you mind making that change. I am not able to do that atm.
Also please bump app version.

Thank you!

2016-10-13 20:51 UTC, irritanterik commented on lib/folderFlows.js
> +      updateFlowEnabled(flow, enabled)
will look into it.

2016-10-13 21:55 UTC, irritanterik commented
Done.

2016-10-14 07:21 UTC, matjaz requested changes

2016-10-14 07:21 UTC, matjaz commented on lib/folderFlows.js
> +    .forEach(flowId => { flowsFiltered.push(flows[flowId]) })
please use `.map`

2016-10-14 17:55 UTC, irritanterik commented
Done. And finally understand .map 👍

2016-10-14 18:00 UTC, matjaz requested changes

2016-10-14 18:00 UTC, matjaz commented on lib/folderFlows.js
> -    folderIds.push(folderId)
this should not be removed.

2016-10-14 18:01 UTC, matjaz requested changes

2016-10-14 18:01 UTC, matjaz commented on lib/folderFlows.js
> -    folderIds.push(folderId)
this should not be removed

2016-10-14 18:02 UTC, matjaz commented
filter/map/reduce is pretty powerfull

2016-10-14 18:04 UTC, merged

2016-10-14 18:05 UTC, matjaz commented
Thank you and sorry for nagging :}

2016-10-14 18:06 UTC, irritanterik commented
No problem. Best way to learn it the good way (and prevent bugs).