Added firmware checks
matjaz/info.matjaz.candy pull request #9
Opened 2016-10-19 22:51 UTC by irritanterik

https://github.com/matjaz/info.matjaz.candy/issues/5

2016-10-20 08:44 UTC, matjaz requested changes
thanks!

2016-10-20 08:44 UTC, matjaz commented on lib/system.js
> +    return result
no need for then function

2016-10-20 08:44 UTC, matjaz commented on lib/systemFlows.js
> +  system.getUpdateInfo().then(function (updateInfo) {
use `Promise.all([system.getSystemInfo(), system.getUpdateInfo()])` for parallel requests

2016-10-20 08:44 UTC, matjaz commented on lib/systemFlows.js
> +    callback(null, (result.length && result[0].version))
condition callback second params should be boolean.
sth like `callback(null, !!(result.length && result[0].version))`

2016-10-20 08:44 UTC, matjaz commented on lib/systemFlows.js
> +    if (checkActionSystemNewFirmwareTimeout) clearTimeout(checkActionSystemNewFirmwareTimeout)
you're mixing `setInterval` with `clearTimeout`.
We want to be notified always for new versions, but only once for same version. So we need something as `latestTriggeredVersion` state, but trigger only when `newVersion !== currentVersion`.

2016-10-20 08:45 UTC, matjaz commented
also please resolve conflicts

2016-10-20 08:46 UTC, matjaz commented on lib/systemFlows.js
> +    if (checkActionSystemNewFirmwareTimeout) clearTimeout(checkActionSystemNewFirmwareTimeout)
we could cache `currentVersion` on boot.

2016-10-20 08:59 UTC, irritanterik commented
Thanks! Bizarre clearTimeout works with a Interval :). Will push changes later this week.

2016-10-20 09:02 UTC, irritanterik commented on lib/systemFlows.js
> +    if (checkActionSystemNewFirmwareTimeout) clearTimeout(checkActionSystemNewFirmwareTimeout)
great suggestion

2016-10-20 09:03 UTC, irritanterik commented on lib/systemFlows.js
> +    callback(null, (result.length && result[0].version))
Was not aware my code not resulted in a boolean. Will look into !!.

2016-10-21 18:33 UTC, matjaz approved these changes

2016-10-21 18:33 UTC, matjaz commented
please resolve conflicts

2016-10-23 17:05 UTC, merged

2016-10-25 18:24 UTC, irritanterik commented
Have them resolve. Because of DNS issues not able to sync them atm.

2016-10-21 20:33 GMT+02:00 Matjaž Lipuš <notifications@github.com>:

> please resolve conflicts
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matjaz/info.matjaz.candy/pull/9#issuecomment-255438553>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOhu1L1mwgvRXucyiHxjo-TBqnwUFcO3ks5q2QVogaJpZM4KbitB>
> .
>